### ISSUE TITLE
Apostrophe, Book 4, "sdeined"

### ISSUE THREAD

**Issue by kingrpaul** [standardebooks/john-milton_paradise-lost#3]
Apostrophe at the beginning of “sdeined” to hold the space of the missing “di” in `<span>I sdeined subjection, and thought one step higher</span>` from book-4.xhtml.

Source: [Wikisource](https://en.wikisource.org/wiki/Page:Paradise_lost_by_Milton,_John.djvu/117)

**Comment by acabal** [comment]
Thanks, this should be fixed now!
